# See: https://github.com/dogmatists/dogma.cpp/actions?query=workflow:CI
---
name: CI
on:
  push:
    branches: [master]
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**.hpp.in'
  pull_request:
    branches: [master]
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**.hpp.in'
jobs:
  lint:
    name: Lint C++ code
    runs-on: ubuntu-18.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Record the Clang version
        run: clang --version
      - name: Record the GCC version
        run: gcc --version
      - name: Check syntax using Clang
        run: make lint CXX=clang
      - name: Check syntax using GCC
        run: make lint CXX=gcc
  test:
    name: Run unit tests
    runs-on: ubuntu-18.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Record the Clang version
        run: clang --version
      - name: Record the GCC version
        run: gcc --version
      - name: Run unit tests using Clang
        run: make test CXX=clang -B
        env:
          RUBYOPT: -W0
      - name: Run unit tests using GCC
        run: make test CXX=gcc -B
        env:
          RUBYOPT: -W0
